/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ada2;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author wmgc5
 */
public class Vista extends javax.swing.JFrame {
    ManejoFichero fichero = new ManejoFichero();
    

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
       // JOptionPane.showMessageDialog(null, "No se ha cargado ningún documento");
       
        matriculajTextField1.setEnabled(false);
        nombresjTextField1.setEnabled(false);
        apellidoPjTextField1.setEnabled(false);
        apellidoMjTextField1.setEnabled(false);
        MateriajTextField1.setEnabled(false);
        CalificacionjTextField2.setEnabled(false);
        //setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    public void cierre(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
 
            });
            this.setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
 
    public void confirmarSalida(){
     int valor= JOptionPane.showConfirmDialog(this, "¿Estas seguro de cerrar la aplicacion?", JOptionPane.YES_NO_OPTION);
     if (valor==JOptionPane.YES_OPTION){
         JOptionPane.showMessageDialog(null, "Gracias por su visita", JOptionPane.INFORMATION_MESSAGE);
         System.exit(0);
     }
 }

 */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        matriculajTextField1 = new javax.swing.JTextField();
        apellidoPjTextField1 = new javax.swing.JTextField();
        apellidoMjTextField1 = new javax.swing.JTextField();
        nombresjTextField1 = new javax.swing.JTextField();
        MateriajTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CalificacionjTextField2 = new javax.swing.JTextField();
        importarbienjButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ventanaCerrada(evt);
            }
        });

        jLabel1.setText("Matricula");

        jLabel2.setText("Apellido P");

        jLabel3.setText("Apellido M");

        jLabel4.setText("Nombres");

        matriculajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculajTextField1ActionPerformed(evt);
            }
        });

        apellidoPjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoPjTextField1ActionPerformed(evt);
            }
        });

        apellidoMjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMjTextField1ActionPerformed(evt);
            }
        });

        nombresjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresjTextField1ActionPerformed(evt);
            }
        });

        MateriajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriajTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Materia");

        jLabel6.setText("Calificacion");

        CalificacionjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalificacionjTextField2ActionPerformed(evt);
            }
        });

        importarbienjButton1.setText("Importar");
        importarbienjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarbienjButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exportar CSV");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Adelante");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Exportar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MateriajTextField1)
                            .addComponent(apellidoMjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(apellidoPjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(matriculajTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(nombresjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(CalificacionjTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(importarbienjButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matriculajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apellidoPjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidoMjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombresjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MateriajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CalificacionjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(importarbienjButton1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public  void confirmarSalida(){
        String opciones[]={"Cerrar sin exportar","Cancelar"};
    int opcion = JOptionPane.showOptionDialog(this, "Estás seguro de salir de la aplicacion, no se ha generado el archivo de calificaciones", "PELIGRO", 0, 0, null, opciones, this);
    if(opcion==JOptionPane.YES_OPTION){
        System.exit(0);
    }
    }
    public void ventanaCerrada(WindowEvent evt) {
        if(fichero.confirmarCaptura()&&fichero.getImportarConfirmado()!=0){
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            confirmarSalida();
        }
      
      

    }

    private void apellidoPjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPjTextField1ActionPerformed
        // TODO add your handling code here:
        apellidoPjTextField1.setEnabled(false);
    }//GEN-LAST:event_apellidoPjTextField1ActionPerformed

    private void matriculajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculajTextField1ActionPerformed
        // TODO add your handling code here:
        matriculajTextField1.setEnabled(false);
    }//GEN-LAST:event_matriculajTextField1ActionPerformed

    private void apellidoMjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMjTextField1ActionPerformed
        // TODO add your handling code here:
        apellidoMjTextField1.setEnabled(false);
    }//GEN-LAST:event_apellidoMjTextField1ActionPerformed

    private void nombresjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresjTextField1ActionPerformed
        // TODO add your handling code here:
        nombresjTextField1.setEnabled(false);
    }//GEN-LAST:event_nombresjTextField1ActionPerformed

    private void MateriajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriajTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MateriajTextField1ActionPerformed

    private void CalificacionjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalificacionjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalificacionjTextField2ActionPerformed

    private void importarbienjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarbienjButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos csv", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        /*
        int seleccionar = seleccionarArchivo.showOpenDialog(this);
        if(seleccionar == JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            guardarArchivo(archivo);
        }
        */

        if(seleccionarArchivo.showDialog(this, "ABRIR CSV")==JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            if(archivo.getName().endsWith("csv")){
                fichero.importarArchivos(archivo);
                if(fichero.getCantidadColumnas()==4){
                    
                    MateriajTextField1.setEnabled(true);
                   CalificacionjTextField2.setEnabled(true);
  
                    fichero.inicio(matriculajTextField1, apellidoPjTextField1, apellidoMjTextField1, nombresjTextField1);
                    fichero.setImportarConfirmado();
                       
                    JOptionPane.showMessageDialog(null, "Archivo seleccionado de forma correcta");
                }else{
                    JOptionPane.showMessageDialog(null, "Cantidad de columnas incorrectas");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "El archivo seleccionado no tiene la extension csv");
            }
            
           
            /*
            if(archivo.endsWith("csv")){

            }
            */

        }

    }//GEN-LAST:event_importarbienjButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        /*
        ListaAlumnos nuevoAlumno = new ListaAlumnos();
        nuevoAlumno.setMatricula(matriculajTextField1.getText());
        nuevoAlumno.setPrimerApellido(apellidoPjTextField1.getText());
        nuevoAlumno.setSegundoApellido(apellidoMjTextField1.getText());
        nuevoAlumno.setNombres(nombresjTextField1.getText());
        listaAlumnos.add(nuevoAlumno);
        
        */
        fichero.guardarAlumno(matriculajTextField1, MateriajTextField1, CalificacionjTextField2);
        
       
        fichero.borrarAlumnos(fichero.getNavegador());
        if(fichero.confirmarCaptura()){
            MateriajTextField1.setEnabled(false);
            CalificacionjTextField2.setEnabled(false);
            matriculajTextField1.setText("");
       
            apellidoPjTextField1.setText("");
           
            apellidoMjTextField1.setText("");
            
            nombresjTextField1.setText("");
            MateriajTextField1.setText("");
            
            CalificacionjTextField2.setText("");
            jButton2.setEnabled(false);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos csv", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        /*
        int seleccionar = seleccionarArchivo.showOpenDialog(this);
        if(seleccionar == JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            guardarArchivo(archivo);
        }
        */
        if(fichero.getImportarConfirmado()==1){

            if(fichero.confirmarCaptura()){
                if(seleccionarArchivo.showDialog(this, "GUARDAR CSV")==JFileChooser.APPROVE_OPTION){
                    File archivo =seleccionarArchivo.getSelectedFile();
                    if(archivo.getName().endsWith("csv")){
                        fichero.exportarArchivo(archivo);
                        
                        
                       
                        
        
                    }else{
                        JOptionPane.showMessageDialog(null, "Se debe agregar la extension .csv");
                    }
                    
                   
                    /*
                    if(archivo.endsWith("csv")){
        
                    }
                    
        */
                }        
            }else{
                JOptionPane.showMessageDialog(null, "No se han registrado todas las calificaciones");
            }
            
            
            

        }
        else{
            JOptionPane.showMessageDialog(null, "DEBES IMPORTAR EL ARCHIVO CSV");

        }
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fichero.atras();
        fichero.inicio(matriculajTextField1, apellidoPjTextField1, apellidoMjTextField1, nombresjTextField1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        fichero.delante();
        fichero.inicio(matriculajTextField1, apellidoPjTextField1, apellidoMjTextField1, nombresjTextField1);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
        seleccionarArchivo.setFileFilter(filtro);
        /*
        int seleccionar = seleccionarArchivo.showOpenDialog(this);
        if(seleccionar == JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            guardarArchivo(archivo);
        }
        */
        if(fichero.getImportarConfirmado()==1){

            if(fichero.confirmarCaptura()){
                if(seleccionarArchivo.showDialog(this, "GUARDAR PDF")==JFileChooser.APPROVE_OPTION){
                    File archivo =seleccionarArchivo.getSelectedFile();
                    if(archivo.getName().endsWith("pdf")){
                        fichero.exportarArchivopdf(archivo);
                        
                        
                       
                        
        
                    }else{
                        JOptionPane.showMessageDialog(null, "Se debe agregar la extension .pdf");
                    }
                    
                   
                    /*
                    if(archivo.endsWith("csv")){
        
                    }
                    
        */
                }        
            }else{
                JOptionPane.showMessageDialog(null, "No se han registrado todas las calificaciones");
            }
            
            
            

        }
        else{
            JOptionPane.showMessageDialog(null, "DEBES IMPORTAR EL ARCHIVO PDF");

        }
         // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CalificacionjTextField2;
    private javax.swing.JTextField MateriajTextField1;
    private javax.swing.JTextField apellidoMjTextField1;
    private javax.swing.JTextField apellidoPjTextField1;
    private javax.swing.JButton importarbienjButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField matriculajTextField1;
    private javax.swing.JTextField nombresjTextField1;
    // End of variables declaration//GEN-END:variables
}
